// D22 catalog builder — pure (no I/O, no import.meta), so the CI gates can
// import it under jest. The CLI shell that writes files is generate-schema.mjs.
// Spec: docs/superpowers/specs/2026-07-03-d22-naturalized-schema-design.md
import { createHash } from "crypto";
import { getAllStandardTagEntries } from "../src/dicom.lookup.js";
import {
    parseVm,
    VR_SCALAR,
    MULTI_VR,
    VR_FORMATS,
    EXCLUDED_TAGS
} from "./schemaRules.mjs";

const SCHEMA_VERSION = "1.0.0";

function bareTag(paren) {
    // "(0008,0008)" -> "00080008"
    const m = paren.match(/^\((\w{4}),(\w{4})\)$/);
    if (!m) {
        throw new Error(`unexpected tag format: ${paren}`);
    }
    return (m[1] + m[2]).toUpperCase();
}

export function buildCatalog() {
    const entries = getAllStandardTagEntries();
    const attributes = {};
    for (const e of entries) {
        const tag = bareTag(e.tag);
        if (EXCLUDED_TAGS.has(tag)) {
            continue;
        }
        parseVm(e.vm); // throws on unclassifiable VM — loud failure
        let vr;
        if (VR_SCALAR[e.vr]) {
            vr = e.vr;
        } else if (MULTI_VR[e.vr]) {
            vr = MULTI_VR[e.vr];
        } else {
            throw new Error(`${tag} ${e.name}: unmapped VR code "${e.vr}"`);
        }
        attributes[tag] = { keyword: e.name, vr, vm: e.vm };
    }
    const sorted = Object.fromEntries(
        Object.entries(attributes).sort(([a], [b]) => a.localeCompare(b))
    );
    const dictionaryHash = createHash("sha256")
        .update(JSON.stringify(sorted))
        .digest("hex")
        .slice(0, 16);
    return {
        version: SCHEMA_VERSION,
        dictionaryHash,
        vrFormats: VR_FORMATS,
        attributes: sorted,
        envelope: {
            cardinality: "vm-based", // VM multi -> array, VM 1 -> scalar (D1)
            personName: "componentObject", // {Alphabetic,Ideographic,Phonetic} (D13)
            sequences: "datasetArray", // SQ -> NaturalizedDataset[]
            privateTags: "creatorGrouped", // '<slot>:<creator>' keys (D2b, spec 12.3)
            unknownTags: "preserved", // { vr, Value, rawValue } (spec 12.3)
            rawRetention: "inexactOnly", // raw kept when round-trip inexact (D14)
            bulk: "referenceOrBinary" // {BulkDataURI} | {InlineBinary} | binary
        }
    };
}

export function catalogSource(catalog) {
    const header =
        "// GENERATED by generate/generate-schema.mjs — DO NOT EDIT.\n" +
        "// Normative rule catalog for the naturalized representation (D22).\n" +
        "// Spec: docs/superpowers/specs/2026-07-03-d22-naturalized-schema-design.md\n";
    return `${header}export const naturalizedRules = ${JSON.stringify(
        catalog,
        null,
        2
    )};\n`;
}
